version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:  # ← Add this
      - .env
    environment:
      - FLASK_ENV
      - DATABASE_URL   # ← read from .env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:  # ← Add this
      - .env
    environment:
      - POSTGRES_USER     # ← read from .env
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: