name: Deploy to EC2

on:
  push:
    branches: [ main ]  # or 'master' if that’s your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy project to EC2
      run: |
        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/product-catalog/

    - name: Rebuild and restart Docker container
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/product-catalog
          docker rm -f product-catalog || true
          docker build -t product-catalog .
          docker run -d --name product-catalog -p 80:5000 product-catalog
        EOF